[workspace]

members = [
    "easyfix",
    "easyfix-dictionary",
    "easyfix-messages",
#"easyfix-session",
]

[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
