[package]
name = "easyfix"
version = "0.3.3"
authors = ["Łukasz Dańko <lukasz.danko@gmail.com>"]
license = "MIT"
description = "Easy FIX (Financial Information Exchange) engine."
repository = "https://github.com/ldanko/easyfix"
readme = "README.md"
edition = "2021"

[dependencies]
easyfix-dictionary = { version = "0.3.0", path = "../easyfix-dictionary" }
easyfix-messages = { version = "0.3.1", path = "../easyfix-messages" }
easyfix-session = { version = "0.1.3", path = "../easyfix-session" }
